version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - web

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3001:3000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - MONGODB_URI=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    networks:
      - web

volumes:
  mongo_data:
    driver: local

networks:
  web:
    external: false
