# Name of your application. Used to uniquely configure containers.
service: url_shortener

# Name of the container image.
image: nikos83/url_shortener

# Deploy to these servers.
servers:
  web:
    hosts:
      - 146.59.44.11
    # labels:
    #   traefik.http.routers.deanout_secure.entrypoints: websecure
    #   traefik.http.routers.deanout_secure.rule: Host(`poauto.pl`)
    #   traefik.http.routers.deanout_secure.tls: true
registry:
  username: nikos83
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

ssh:
  user: debian

accessories:
  mongo:
    image: mongo:latest
    host: 146.59.44.11 # Assuming MongoDB runs on the same server
    port: 27017
    directories:
      - mongo_data:/data/db

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.websecure.address: ":443"

volumes:
  - "storage:/rails/storage"
# Configure custom arguments for Traefik. Be sure to reboot traefik when you modify it.
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# If your app is using the Sprockets gem, ensure it sets `config.assets.manifest`.
# See https://github.com/basecamp/kamal/issues/626 for details
#
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Configure the role used to determine the primary_host. This host takes
# deploy locks, runs health checks during the deploy, and follow logs, etc.
#
# Caution: there's no support for role renaming yet, so be careful to cleanup
#          the previous role on the deployed hosts.
# primary_role: web

# Controls if we abort when see a role with no hosts. Disabling this may be
# useful for more complex deploy configurations.
#
# allow_empty_roles: false
