# Name of your application. Used to uniquely configure containers.
service: url_shortener

# Name of the container image.
image: nikos83/url_shortener

# Deploy to these servers.
servers:
  web:
    hosts:
      - srv19.mikr.us
    labels:
      traefik.http.routers.url_shortener.rule: "Host(`srv19.mikr.us`)"
      traefik.http.routers.url_shortener.entrypoints: "web"
      traefik.http.services.url_shortener_service.loadbalancer.server.port: "3000"
      traefik.http.routers.url_shortener.tls: "false"

    options:
      network: "private"
registry:
  username: nikos83
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

ssh:
  user: deploy
  port: 10232

accessories:
  mongo:
    image: mongo:latest
    host: srv19.mikr.us # Assuming MongoDB runs on the same server
    port: 27017
    directories:
      - mongo_data:/data/db
    options:
      network: "private"

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
  clear:
    MONGODB_URI: mongodb://url_shortener-mongo:27017/url_shortener_production
    ROOT_URL: http://poauto.pl

# traefik:
#   options:
#     publish:
#       - "443:443"
#     network: "private"
#   args:
#     entryPoints.websecure.address: ":443"
traefik:
  options:
    publish:
      - "40166:40166"
      - "80:80"
      - "443:443"
    network: "private"
  args:
    # entryPoints.web.address: ":40166"
    entryPoints.web.address: ":40166"
    entryPoints.websecure.address: ":443"
    api.dashboard: "true" # Enable the dashboard
    api.insecure: "true"

volumes:
  - "storage:/rails/storage"
