# Nazwa Twojej aplikacji. Używana do unikalnej konfiguracji kontenerów.
service: url_shortener

# Nazwa obrazu kontenera.
image: nikos83/url_shortener

# Etykiety Traefik przypisane do usługi aplikacji
labels:
  traefik.enable: "true"
  traefik.http.routers.url_shortener.rule: "Host(`poauto.pl`)"
  traefik.http.routers.url_shortener.entrypoints: "web"
  traefik.http.routers.url_shortener.service: "url_shortener_service"
  traefik.http.routers.url_shortener.tls: "false"
  traefik.http.services.url_shortener_service.loadbalancer.server.port: "3000" # Zamień na port wewnętrzny Twojej aplikacji, jeśli jest inny

# Wdrażaj na tych serwerach.
servers:
  web:
    hosts:
      - srv19.mikr.us
    options:
      network: "private"

registry:
  username: nikos83
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

ssh:
  user: deploy
  port: 10232

accessories:
  mongo:
    image: mongo:latest
    host: srv19.mikr.us
    port: 27017
    directories:
      - mongo_data:/data/db
    options:
      network: "private"

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - ROOT_URL
  clear:
    MONGODB_URI: mongodb://url_shortener-mongo:27017/url_shortener_production

traefik:
  options:
    publish:
      - "80:80" # Zmieniono na port 80 dla standardowego dostępu HTTP
    network: "private"
  args:
    entryPoints.web.address: ":80"

volumes:
  - "storage:/rails/storage"
