# Name of your application. Used to uniquely configure containers.
service: url_shortener

# Name of the container image.
image: nikos83/url_shortener

# Deploy to these servers.
servers:
  web:
    hosts:
      - 146.59.44.11
    labels:
      traefik.http.routers.deanout_secure.entrypoints: websecure
      traefik.http.routers.deanout_secure.rule: Host(`poauto.pl`)
      traefik.http.routers.deanout_secure.tls: true
    network: "url_shortener_network" # Nazwa sieci, która będzie współdzielona między kontenerami

registry:
  username: nikos83
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

ssh:
  user: debian

accessories:
  mongo:
    image: mongo:latest
    host: url_shortener-mongo # Użyj nazwy hosta kontenera, nie adresu IP
    port: 27017
    directories:
      - mongo_data:/data/db
    network: "url_shortener_network"

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
  clear:
    MONGODB_URI: mongodb://url_shortener-mongo:27017/url_shortener_production # Użyj nazwy hosta kontenera

traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.websecure.address: ":443"
  network: "url_shortener_network"

volumes:
  - "storage:/rails/storage"
