development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: url_shortener_development
      hosts:
        - localhost:27017
      options:

  options:

  driver_options:
test:
  clients:
    default:
      database: url_shortener_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: url_shortener_production
      hosts:
        - localhost:27017
      options:
